# Generated by Django 6.0 on 2026-01-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_exam_end_time_remove_exam_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='total_marks',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Auto-calculated from question marks', verbose_name='Total Marks'),
        ),
    ]
