# Generated by Django 6.0 on 2026-01-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_exam_total_marks'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examattempt',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='exam',
            name='pass_percentage',
            field=models.PositiveIntegerField(default=40, help_text='Minimum percentage required to pass (e.g., 40 for 40%)', verbose_name='Pass Percentage'),
        ),
    ]
