# Generated by Django 6.0 on 2026-01-01 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_examattempt_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Grade 10 - Section A (2025)', max_length=100, verbose_name='Class Name')),
                ('description', models.TextField(blank=True, help_text='Additional details about this class', verbose_name='Description')),
                ('year', models.IntegerField(help_text='Year this class is active (e.g., 2025)', verbose_name='Academic Year')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive classes are archived but not deleted', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_classes', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('students', models.ManyToManyField(blank=True, limit_choices_to={'role': 'student'}, related_name='student_classes', to=settings.AUTH_USER_MODEL, verbose_name='Students')),
            ],
            options={
                'verbose_name': 'Student Class',
                'verbose_name_plural': 'Student Classes',
                'ordering': ['-year', '-created_at'],
                'unique_together': {('name', 'year', 'created_by')},
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='assigned_classes',
            field=models.ManyToManyField(blank=True, help_text='Classes that can take this exam', related_name='assigned_exams', to='myapp.studentclass', verbose_name='Assigned Classes'),
        ),
    ]
