# Generated by Django 6.0 on 2026-01-01 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_studentclass_exam_assigned_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='student_class',
            field=models.ForeignKey(help_text='The class context in which this exam was taken', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='myapp.studentclass', verbose_name='Class'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['student', 'exam', 'student_class'], name='myapp_exama_student_921841_idx'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['student_class', 'exam', '-started_at'], name='myapp_exama_student_a52902_idx'),
        ),
    ]
