# Generated by Django 6.0 on 2026-01-02 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_add_class_scope_to_exam_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclass',
            name='allow_self_enrollment',
            field=models.BooleanField(default=False, help_text='Students can join using the enrollment code', verbose_name='Allow Self-Enrollment'),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='enrollment_code',
            field=models.CharField(blank=True, help_text='Unique code students can use to self-enroll', max_length=8, null=True, unique=True, verbose_name='Enrollment Code'),
        ),
    ]
