# Generated by Django 6.0 on 2026-01-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_add_enrollment_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='Optional: Explain why the correct answer is correct to help students learn.', null=True, verbose_name='Explanation'),
        ),
    ]
