# Generated by Django 6.0 on 2026-01-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_question_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='has_violation',
            field=models.BooleanField(default=False, verbose_name='Violation Detected'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='violation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Violation Reason'),
        ),
    ]
