# Generated by Django 6.0 on 2026-01-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.CharField(choices=[('English', 'English'), ('Social Science', 'Social Science'), ('Science', 'Science'), ('Mathematics', 'Mathematics'), ('தமிழ்', 'தமிழ்')], help_text='Select subject from predefined list', max_length=100, verbose_name='Subject'),
        ),
    ]
