# Generated by Django 6.0 on 2026-01-24 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_exam_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='is_published',
        ),
    ]
