# Generated by Django 6.0 on 2026-01-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_is_published_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='question_order',
            field=models.JSONField(blank=True, help_text='Stores the randomized question IDs in order for this attempt', null=True, verbose_name='Question Order'),
        ),
    ]
