# Generated by Django 6.0 on 2026-01-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_add_question_order_to_examattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('practice', 'Practice'), ('test', 'Test')], default='test', help_text='Practice: Unlimited attempts | Test: Single attempt only', max_length=20, verbose_name='Exam Type'),
        ),
    ]
