# Generated by Django 6.0 on 2026-01-27 16:37

from django.db import migrations, models


def set_existing_attempt_modes(apps, schema_editor):
    """
    Set attempt_mode for existing ExamAttempt records based on the exam's type.
    - For 'test' exams: set attempt_mode to 'test'
    - For 'practice' exams: set attempt_mode to 'practice'
    """
    ExamAttempt = apps.get_model('myapp', 'ExamAttempt')
    
    attempts_to_update = []
    for attempt in ExamAttempt.objects.select_related('exam').all():
        if attempt.exam.exam_type == 'test':
            attempt.attempt_mode = 'test'
        else:  # practice or practice_test (old practice exams)
            attempt.attempt_mode = 'practice'
        attempts_to_update.append(attempt)
    
    if attempts_to_update:
        ExamAttempt.objects.bulk_update(attempts_to_update, ['attempt_mode'])


def update_exam_types(apps, schema_editor):
    """
    Update existing exam types:
    - 'practice' -> 'practice_test' (new default)
    - 'test' -> 'test' (unchanged)
    """
    Exam = apps.get_model('myapp', 'Exam')
    
    # Convert old 'practice' exams to 'practice_test'
    Exam.objects.filter(exam_type='practice').update(exam_type='practice_test')


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_add_exam_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='attempt_mode',
            field=models.CharField(choices=[('practice', 'Practice'), ('test', 'Test')], default='test', help_text='Practice attempts are for learning; Test attempts count for leaderboard', max_length=20, verbose_name='Attempt Mode'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('practice_test', 'Practice & Test'), ('test', 'Test')], default='practice_test', help_text='Practice & Test: Unlimited practice + One test attempt | Test: Single attempt only', max_length=20, verbose_name='Exam Type'),
        ),
        migrations.RunPython(set_existing_attempt_modes, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(update_exam_types, reverse_code=migrations.RunPython.noop),
    ]
