# Generated by Django 6.0 on 2026-05-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_question_options_alter_studentanswer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='chapter',
            field=models.CharField(blank=True, max_length=200, verbose_name='Chapter/Topic/Category'),
        ),
        migrations.AddField(
            model_name='exam',
            name='grade',
            field=models.CharField(blank=True, max_length=50, verbose_name='Grade/Standard'),
        ),
    ]
