# Generated by Django 6.0 on 2026-05-03 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_exam_chapter_exam_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_cloned',
            field=models.BooleanField(default=False, help_text='Indicates if this exam is a duplicate working copy of an original exam from the bank.', verbose_name='Is Cloned Copy'),
        ),
        migrations.AlterField(
            model_name='question',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='myapp.school', verbose_name='School'),
        ),
    ]
