# Generated by Django 6.0 on 2026-05-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_exam_is_cloned_alter_question_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='chapter',
            field=models.CharField(max_length=200, verbose_name='Chapter/Topic/Category'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='grade',
            field=models.CharField(max_length=50, verbose_name='Grade/Standard'),
        ),
    ]
