# Generated by Django 6.0 on 2026-05-06 06:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_studentclass_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='code',
            field=models.CharField(help_text='Short globally unique 6-character code used in username generation (e.g., SPHS12). Uppercase letters and numbers only.', max_length=6, unique=True, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='School Code'),
        ),
    ]
