# Generated by Django 6.0 on 2026-06-24 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_alter_school_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAssignmentDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Assigned At')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_dates', to='myapp.exam')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_assignment_dates', to='myapp.studentclass')),
            ],
            options={
                'verbose_name': 'Exam Assignment Date',
                'verbose_name_plural': 'Exam Assignment Dates',
                'unique_together': {('exam', 'student_class')},
            },
        ),
    ]
