# Generated by Django 6.0 on 2026-08-17 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_backfill_examassignmentdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='code',
        ),
    ]
