# Generated by Django 6.0 on 2026-08-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_remove_school_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='grade',
            field=models.CharField(choices=[('Year 1', 'Year 1'), ('Year 2', 'Year 2'), ('Year 3', 'Year 3'), ('Year 4', 'Year 4')], max_length=50, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.CharField(choices=[('Aptitude', 'Aptitude'), ('GATE', 'GATE')], help_text='Select subject from predefined list', max_length=100, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='question',
            name='grade',
            field=models.CharField(blank=True, max_length=50, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(choices=[('Aptitude', 'Aptitude'), ('GATE', 'GATE')], max_length=100, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='grade',
            field=models.CharField(choices=[('Year 1', 'Year 1'), ('Year 2', 'Year 2'), ('Year 3', 'Year 3'), ('Year 4', 'Year 4')], default='Year 1', help_text='Select the grade level for this class', max_length=20, verbose_name='Year'),
        ),
    ]
