# Generated by Django 6.0 on 2026-08-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_alter_exam_grade_alter_exam_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='question',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='studentclass',
            name='grade',
        ),
        migrations.AddField(
            model_name='exam',
            name='department',
            field=models.CharField(blank=True, choices=[('Artificial Intelligence & Data Science', 'Artificial Intelligence & Data Science'), ('Computer Science Engineering', 'Computer Science Engineering'), ('CSE (AI and Machine Learning)', 'CSE (AI and Machine Learning)'), ('Electronics & Communication Engineering', 'Electronics & Communication Engineering'), ('EE (VLSI Design & Technology)', 'EE (VLSI Design & Technology)'), ('Electrical & Electronics Engineering', 'Electrical & Electronics Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Sciences & Humanities', 'Sciences & Humanities'), ('Computer Science & Business Systems', 'Computer Science & Business Systems'), ('CSE (Cyber Security)', 'CSE (Cyber Security)'), ('Information Technology', 'Information Technology'), ('ECE (Advanced Comm. Technology)', 'ECE (Advanced Comm. Technology)'), ('Biomedical Engineering', 'Biomedical Engineering'), ('B.E Mechatronics Engineering', 'B.E Mechatronics Engineering'), ('Civil Engineering', 'Civil Engineering')], max_length=100, verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='question',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='department',
            field=models.CharField(choices=[('Artificial Intelligence & Data Science', 'Artificial Intelligence & Data Science'), ('Computer Science Engineering', 'Computer Science Engineering'), ('CSE (AI and Machine Learning)', 'CSE (AI and Machine Learning)'), ('Electronics & Communication Engineering', 'Electronics & Communication Engineering'), ('EE (VLSI Design & Technology)', 'EE (VLSI Design & Technology)'), ('Electrical & Electronics Engineering', 'Electrical & Electronics Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Sciences & Humanities', 'Sciences & Humanities'), ('Computer Science & Business Systems', 'Computer Science & Business Systems'), ('CSE (Cyber Security)', 'CSE (Cyber Security)'), ('Information Technology', 'Information Technology'), ('ECE (Advanced Comm. Technology)', 'ECE (Advanced Comm. Technology)'), ('Biomedical Engineering', 'Biomedical Engineering'), ('B.E Mechatronics Engineering', 'B.E Mechatronics Engineering'), ('Civil Engineering', 'Civil Engineering')], default='Computer Science Engineering', help_text='Select the department for this class', max_length=100, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='name',
            field=models.CharField(help_text='e.g., AI & DS - Section A (2025)', max_length=100, verbose_name='Class Name'),
        ),
    ]
