# Generated by Django 6.0 on 2026-08-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_remove_exam_grade_remove_question_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='batch',
            field=models.CharField(blank=True, help_text='Admission year range, e.g. 2024–2028', max_length=20, null=True, verbose_name='Batch'),
        ),
    ]
