# Generated by Django 6.0 on 2026-08-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_user_batch'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentclass',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='batch',
            field=models.CharField(default='2024-2028', help_text='Admission year range (e.g., 2024–2028)', max_length=20, verbose_name='Batch'),
        ),
        migrations.RemoveField(
            model_name='studentclass',
            name='year',
        ),
        migrations.AlterUniqueTogether(
            name='studentclass',
            unique_together={('name', 'batch', 'created_by', 'school')},
        ),
        migrations.AlterModelOptions(
            name='studentclass',
            options={'ordering': ['-batch', '-created_at'], 'verbose_name': 'Student Class', 'verbose_name_plural': 'Student Classes'},
        ),
    ]
