# Generated by Django 6.0 on 2026-08-23 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_alter_studentclass_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('timed_out', 'Timed Out'), ('terminated', 'Terminated')], default='in_progress', max_length=20, verbose_name='Attempt Status'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='is_marked_for_review',
            field=models.BooleanField(default=False, verbose_name='Marked for Review'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='state',
            field=models.CharField(choices=[('not_visited', 'Not Visited'), ('visited_unanswered', 'Visited & Unanswered'), ('answered', 'Answered'), ('marked_for_review', 'Marked for Review'), ('answered_marked_for_review', 'Answered & Marked for Review')], default='visited_unanswered', max_length=35, verbose_name='Answer State'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='answered_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Answered At'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_by', to='myapp.choice', verbose_name='Selected Choice'),
        ),
    ]
